{
  "input": {
    "sekoiaio": {
      "intake": {
        "dialect": "NGINX",
        "dialect_uuid": "ab25af2e-4916-40ba-955c-34d2301c1f51"
      }
    },
    "message": "2019/08/25 23:59:53 [error] 9841#9841: *103137592 connect() failed (111: Connection refused) while connecting to upstream, client: 51.255.128.104, server: api.prod.sekoia.io, request: \"GET /v1/apiauth/auth/health HTTP/1.1\", upstream: \"http://10.110.30.121:80/v1/apiauth/auth/health\", host: \"api.sekoia.io\""
  },
  "expected": {
    "message": "2019/08/25 23:59:53 [error] 9841#9841: *103137592 connect() failed (111: Connection refused) while connecting to upstream, client: 51.255.128.104, server: api.prod.sekoia.io, request: \"GET /v1/apiauth/auth/health HTTP/1.1\", upstream: \"http://10.110.30.121:80/v1/apiauth/auth/health\", host: \"api.sekoia.io\"",
    "event": {
      "kind": "error"
    },
    "destination": {
      "address": "api.prod.sekoia.io",
      "domain": "api.prod.sekoia.io"
    },
    "http": {
      "request": {
        "method": "GET"
      },
      "version": "1.1"
    },
    "source": {
      "address": "51.255.128.104",
      "ip": "51.255.128.104"
    },
    "url": {
      "original": "/v1/apiauth/auth/health",
      "path": "/v1/apiauth/auth/health"
    },
    "related": {
      "hosts": [
        "api.prod.sekoia.io"
      ],
      "ip": [
        "51.255.128.104"
      ]
    }
  }
}